CXXFLAGS = -g -std=c++17 -Wall -Wextra -Wpedantic -Werror

all: thrice stderr foreach

clean:
  rm -f thrice stderr foreach

thrice: thrice.cpp
	g++ -o thrice thrice.cpp 

stderr: stderr.cpp
	g++ -o stderr stderr.cpp 

foreach: foreach.cpp
	g++ -o foreach foreach.cpp 




  
