CXXFLAGS = -g -std=c++17 -Wall -Wextra -Wpedantic -Werror

all: box rebuild

clean:
	rm -f box rebuild 

box: box.cpp
	$(CXXFLAGS) g++ -o box box.cpp 

rebuild: rebuild.cpp
	$(CXXFLAGS) g++ -o rebuild rebuild.cpp 





  
