CXXFLAGS = -g -std=c++17 -Wall -Wextra -Wpedantic -Werror

all: thrice stderr foreach

clean:
	rm -f thrice stderr foreach

thrice: thrice.cpp
	gcc -o thrice thrice.cpp 

stderr: stderr.cpp
	gcc -o stderr stderr.cpp 

foreach: foreach.cpp
	gcc -o foreach foreach.cpp 




  
